[package]
name = "synth-designer"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
peg = "0.8.4"
proc-macro2 = "1.0.92"
quote = "1.0.37"
rust-ini = "0.21.1"
syn = "2.0.90"
synth-engine = { path = "../synth-engine" }
thiserror = "2.0.3"
